import type { Unit, Member } from './types';

export const units: Unit[] = [
  { id: '1', name: '1MR' },
  { id: '2', name: '2MR' },
  { id: '3', name: '3MR' },
  { id: '4', name: 'HQ' },
];

export const members: Member[] = [
  {
    id: '1',
    membershipCode: '1MR-31000-0724',
    name: 'John Doe',
    fatherName: 'Richard Doe',
    rank: 'Sergeant',
    trade: 'Infantry',
    serviceNumber: '12345',
    dateOfBirth: new Date('1985-05-20'),
    dateOfEnrolment: new Date('2005-01-15'),
    address: '123 Main St, Anytown, USA',
    phone: '555-1234',
    unitId: '1',
    status: 'Opened',
    isDoubling: false,
    subscriptionStartDate: new Date('2024-07-01'),
    nominee: { name: 'Jane Doe', relation: 'Spouse' },
  },
  {
    id: '2',
    membershipCode: '2MR-31001-0724',
    name: 'Peter Jones',
    fatherName: 'Robert Jones',
    rank: 'Corporal',
    trade: 'Artillery',
    serviceNumber: '67890',
    dateOfBirth: new Date('1990-11-11'),
    dateOfEnrolment: new Date('2010-03-20'),
    address: '456 Oak Ave, Anytown, USA',
    phone: '555-5678',
    unitId: '2',
    status: 'Opened',
    isDoubling: false,
    subscriptionStartDate: new Date('2024-07-01'),
    nominee: { name: 'Mary Jones', relation: 'Mother' },
  },
  {
    id: '3',
    membershipCode: '1MR-31002-0624',
    name: 'Mary Smith',
    fatherName: 'John Smith',
    rank: 'Sergeant',
    trade: 'Signals',
    serviceNumber: '54321',
    dateOfBirth: new Date('1988-02-25'),
    dateOfEnrolment: new Date('2008-06-01'),
    address: '789 Pine Ln, Anytown, USA',
    phone: '555-8765',
    unitId: '1',
    status: 'Closed',
    closureReason: 'Retirement',
    dateOfDischarge: new Date('2024-05-31'),
    isDoubling: false,
    subscriptionStartDate: new Date('2024-06-01'),
    nominee: { name: 'Sam Smith', relation: 'Son' },
  },
  {
    id: '4',
    membershipCode: 'HQ-31003-0524',
    name: 'David Williams',
    fatherName: 'James Williams',
    rank: 'Major',
    trade: 'Staff',
    serviceNumber: '98765',
    dateOfBirth: new Date('1975-08-15'),
    dateOfEnrolment: new Date('1995-09-10'),
    address: '101 Maple Dr, Anytown, USA',
    phone: '555-4321',
    unitId: '4',
    status: 'Opened',
    isDoubling: true,
    subscriptionStartDate: new Date('2024-05-01'),
    nominee: { name: 'Susan Williams', relation: 'Spouse' },
  },
];
